//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int id_binhluan { get; set; }
        public string id_kh { get; set; }
        public Nullable<int> id_parent { get; set; }
        public Nullable<int> id_ctsp { get; set; }
        public string van_ban_binh_luan { get; set; }
        public Nullable<System.DateTime> ngay_binh_luan { get; set; }
        public Nullable<int> danh_gia { get; set; }
    
        public virtual CHITIETSP CHITIETSP { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
