//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETSP()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.BINHLUANs = new HashSet<BINHLUAN>();
        }
    
        public int id_ctsp { get; set; }
        public Nullable<int> id_sp { get; set; }
        public string id_nbh { get; set; }
        public Nullable<int> id_size { get; set; }
        public Nullable<int> id_color { get; set; }
        public Nullable<int> id_brand { get; set; }
        public string id_member { get; set; }
        public Nullable<int> id_nganhhang { get; set; }
        public Nullable<int> id_nhcon { get; set; }
        public Nullable<int> id_nhc3 { get; set; }
        public Nullable<int> so_luong { get; set; }
        public string hinh_sp { get; set; }
    
        public virtual BANGMAU BANGMAU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        public virtual XUATXU XUATXU { get; set; }
        public virtual NGUOIBANHANG NGUOIBANHANG { get; set; }
        public virtual NGANHHANG NGANHHANG { get; set; }
        public virtual NGANHHANGCON NGANHHANGCON { get; set; }
        public virtual NGANHHANGCAP3 NGANHHANGCAP3 { get; set; }
        public virtual KICHCO KICHCO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINHLUAN> BINHLUANs { get; set; }
    }
}
