//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int id_don { get; set; }
        public int id_ctsp { get; set; }
        public string id_nbh { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<decimal> gia_tien { get; set; }
    
        public virtual CHITIETSP CHITIETSP { get; set; }
        public virtual DONHANG DONHANG { get; set; }
        public virtual NGUOIBANHANG NGUOIBANHANG { get; set; }
    }
}
