//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG_QUATANG
    {
        public int id_don { get; set; }
        public int id_qua { get; set; }
        public Nullable<int> so_diem_da_su_dung { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual QUATANG QUATANG { get; set; }
    }
}
