//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
            this.TINTUCs = new HashSet<TINTUC>();
        }
    
        public int id_nv { get; set; }
        public string ho_ten { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string dia_chi { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string avatar { get; set; }
        public Nullable<int> tinh_trang_nv { get; set; }
        public string id_cv { get; set; }
        public Nullable<int> id_pb { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TINTUC> TINTUCs { get; set; }
    }
}
