//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUONGXA
    {
        public string id_px { get; set; }
        public string ten_px { get; set; }
        public string id_quan { get; set; }
    
        public virtual QUANHUYEN QUANHUYEN { get; set; }
    }
}
