//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUATANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUATANG()
        {
            this.DONHANG_QUATANG = new HashSet<DONHANG_QUATANG>();
        }
    
        public int id_qua { get; set; }
        public string ten_qua { get; set; }
        public Nullable<int> so_diem_can { get; set; }
        public string mo_ta_qua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG_QUATANG> DONHANG_QUATANG { get; set; }
    }
}
