//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TINTUC()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public int id_tin_tuc { get; set; }
        public string tieu_de { get; set; }
        public string noi_dung { get; set; }
        public Nullable<System.DateTime> ngay_dang { get; set; }
        public Nullable<int> id_theloai { get; set; }
        public string image_tintuc { get; set; }
    
        public virtual THELOAITIN THELOAITIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
