//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANCHUYEN
    {
        public int id_vc { get; set; }
        public Nullable<decimal> phi_vc { get; set; }
        public Nullable<int> id_don { get; set; }
        public Nullable<int> id_shipper { get; set; }
        public Nullable<System.DateTime> ngay_giao_hang { get; set; }
        public Nullable<int> trang_thai_giao_hang { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SHIPPER SHIPPER { get; set; }
    }
}
